package:
  name: r-gglogger
  version: 0.1.4

source:
  git_url: https://github.com/pwwang/gglogger
  git_rev: 99e9ace2f1bb9c24488f3ca8f933627c93e91219 # on 10/01/2024

build:
  number: 2
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  host:
    - r-base
    - r-ggplot2
    - r-cli

  run:
    - r-base
    - r-ggplot2
    - r-cli

test:
  commands:
    - $R -e "library('gglogger')"

about:
  home: https://github.com/pwwang/gglogger
  license: MIT
  summary: Logs the calls used to create ggplot2 objects.
  license_family: MIT
  license_file: LICENSE.md
