package:
  name: r-gglogger
  version: 0.1.5

source:
  git_url: https://github.com/pwwang/gglogger
  git_rev: 0.1.5

build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  host:
    - r-base
    - r-ggplot2
    - r-cli

  run:
    - r-base
    - r-ggplot2
    - r-cli

test:
  commands:
    - $R -e "library('gglogger')"

about:
  home: https://github.com/pwwang/gglogger
  license: MIT
  summary: Logs the calls used to create ggplot2 objects.
  license_family: MIT
  license_file: LICENSE.md
